# Generated by Django 5.2.12 on 2026-05-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultura', models.CharField(max_length=100)),
                ('umidade', models.FloatField()),
                ('ph', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('recomendacao', models.TextField()),
            ],
        ),
    ]
