# Generated by Django 5.2.14 on 2026-06-01 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analise',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analises_solos', to=settings.AUTH_USER_MODEL),
        ),
    ]
