# Generated by Django 5.2.14 on 2026-06-08 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0002_analise_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtor',
            name='data_cadastro',
        ),
        migrations.AddField(
            model_name='produtor',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='produtores', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
