# Generated by Django 5.2.14 on 2026-06-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0003_remove_produtor_data_cadastro_produtor_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturaAgricola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('umidade_min', models.FloatField()),
                ('umidade_max', models.FloatField()),
                ('ph_min', models.FloatField()),
                ('ph_max', models.FloatField()),
                ('temperatura_min', models.FloatField()),
                ('temperatura_max', models.FloatField()),
                ('descricao', models.TextField(blank=True)),
                ('fonte', models.CharField(default='EMBRAPA', max_length=50)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CulturaMonitorada',
        ),
    ]
